### ISSUE TITLE
SinkInputInfo to SinkInputInfoInternal

### ISSUE THREAD

**Issue by alexandruioanp** [jnqnfe/pulse-binding-rust#1]
Hi! I'm a Rust beginner, so I might be missing something obvious. I want to subscribe to the server and get notified when the volume of any sink input changes. I've set up a callback using `get_sink_input_info` and it's firing as intended, but the parameter of interest is of type SinkInputInfoInternal. How can I convert this to the proper Rust `struct` type?

**Comment by jnqnfe** [comment]
Hi, both of these structs are identical, it was only duplicated in the binding crate to attach some documentation. So there's no need to do anything, use it as is (there are no methods to differentiate them), or transmute between them if you like (std::mem::transmute) (which you have to wrap in an unsafe block - Rust will only allow this if the structs are identical sizes, which they are).

I'll get some `From` methods implemented soon to hide the transmuting :)

**Comment by jnqnfe** [comment]
Done :)
