### ISSUE TITLE
Send+Sync for libpulse_simple_binding::Simple

### ISSUE THREAD

**Issue by MOZGIII** [jnqnfe/pulse-binding-rust#16]
I need `Send`+`Sync` for `libpulse_simple_binding::Simple` for pretty much the same reason at #14.

I didn't look into it and don't know if it's actually safe, however is the ususal cases it is...

**Comment by jnqnfe** [comment]
Ok, I will look into it. I think this will be fine, but I don't know why I didn't enable it before and don't want to rush out a new release right this second without considering it properly. I'll try to find a moment to do so over the next few days or so.

**Comment by jnqnfe** [comment]
addressed in new version just released :)
