### ISSUE TITLE
[libpulse-binding] how to manage mainloop in callbacks

### ISSUE THREAD

**Issue by mitchhentges** [jnqnfe/pulse-binding-rust#21]
Hey, thanks for creating this higher-level abstraction for `pulse`!
How would you recommend managing `mainloop` when I'm dealing with callbacks?
For example:

```
let mainloop: Rc<RefCell<Mainloop>> = ...
let context = Rc<RefCell<Context>> = ...

let op = {
    let mainloop = mainloop.clone();
    context.borrow().introspect().get_server_info(move |info| {
        let op = context.borrow().introspect().get_sink_info_by_name(&info.default_sink_name.unwrap(), move |_| {
            println!("neat");
        });
        # loop
        #     mainloop.iterate
        #     break if op.get_state() == Done
        #
    })
}

# loop
#     mainloop.iterate => at this point, callback is called
#     break if op.get_state() == Done
#
```

I'm running into an issue where `mainloop` is in use when my callback is called. So, when I need to wait for my nested operation (`get_sink_info_by_name(...)`), I can't borrow `mainloop` to iterate, since it's already in use.

How would you recommend handling this?

**Comment by mitchhentges** [comment]
One approach is to not manually wait on each operation, but rather to just run the mainloop and "let fly", e.g.:

```
let mut mainloop = Mainloop::new().unwrap();
let context = Rc::new(RefCell::new(context));
let introspector = context.borrow().introspect();
{
    let context = context.clone();
    introspector.get_server_info(move |info| {
        context.borrow().introspect().get_sink_info_by_name(
            &info.default_sink_name.clone().unwrap(),
            move |list_result| {
                if let ListResult::Item(sink_info) = list_result {
                    dbg!(sink_info);
                }
            });
    });
}
mainloop.run().unwrap();
```

**Comment by jnqnfe** [comment]
I can only respond to this very briefly.

The major issue that I see with the original example code, from a quick look at it, is that you seem to be following a flawed concept of mainloop execution.

You have created a callback which, as you correctly point out, is executed by the mainloop iteration done at the bottom. However, you also are trying to perform an operation relating to mainloop execution within the callback itself, which goes against the concepts of using the mainloop. I.e. you are trying to force a mainloop iteration, from within the execution of a mainloop iteration itself.

While recursive function calling may be a perfectly legitimate programming concept, you just can't do that here (afaik).

**Comment by mitchhentges** [comment]
True, I suppose my approach required that operations could be run sequentially
```
|-----------------mainloop--------------|
|------------------|   |----------------|
    operation 1            operation 2
 (get server info)      (get sink info)
```
Though, in actuality, if my callback is triggering the next operation, then there's some overlap:
```
|-----------------mainloop--------------|
|-----------------------|
    operation 1      |------------------|
 (get server info)        operation 2
                        (get sink info)
```
Interesting! Thanks for the insight :smile:
