### ISSUE TITLE
IterateResult is misspelled

### ISSUE THREAD

**Issue by HyperHamster** [jnqnfe/pulse-binding-rust#4]
https://github.com/jnqnfe/pulse-binding-rust/blob/master/pulse-binding/src/mainloop/standard.rs#L224

Technically fixing this would be a breaking change and it can be trivially worked around with `InterateResult as IterateResult`, but I would personally appreciate it.

@jnqnfe

**Comment by jnqnfe** [comment]
Damn. Thanks for reporting. Fixed in v2.2 just released :)
