### ISSUE TITLE
libpulse-binding build on docs.rs fails for version 2.24

### ISSUE THREAD

**Issue by agraven** [jnqnfe/pulse-binding-rust#40]
The build error stems from `libpulse_sys::version::actual` module being defined twice, presumably either because of incorrectly written version feature guards or a mistake in a `Cargo.toml` somewhere.

Link to the build error: https://docs.rs/crate/libpulse-binding/2.24.0/builds/416491

**Comment by jnqnfe** [comment]
Hi. Yes, I made a small mistake in version 1.19.0 of `libpulse-sys` which I fixed in version 1.19.1. I've had to request a rebuild of the dependant sibling crates like `libpulse-binding` here: https://github.com/rust-lang/docs.rs/issues/1454 So far no response from the docs.rs team.

**Comment by jnqnfe** [comment]
Resolved with release of new versions. :)
