### ISSUE TITLE
Soundness issue

### ISSUE THREAD

**Issue by Freax13** [jnqnfe/pulse-binding-rust#42]
`MainloopInner::get_api` dereferences the user accessible raw pointer `MainloopInner::api`.

This is unsound because a user could safely modify `MainloopInner::api` and call `MainloopInner::get_api` to cause UB.

**Comment by jnqnfe** [comment]
A user could only *safely* do that if they had a pointer of the correct type (`*const MainloopApi`), and thus it would only be unsound if they were changing it to one belonging to a different mainloop object. They would have to use an *unsafe* code block to transmute some other pointer to be able to force it into the attribute.

That said, I don't believe that users have any actual need to ever mutate the objects once they've been created, and a function can be offered for object creation to support the needs of the glib-mainloop crate, so I can and will rework this to make the attributes private.

**Comment by Freax13** [comment]
> A user could only _safely_ do that if they had a pointer of the correct type (`*const MainloopApi`), and thus it would only be unsound if they were changing it to one belonging to a different mainloop object. They would have to use an _unsafe_ code block to transmute some other pointer to be able to force it into the attribute.

Creating an invalid pointer is as easy as `0xdead_beefusize as *const MainloopInner` and doesn't require any unsafe code.

**Comment by jnqnfe** [comment]
> Creating an invalid pointer is as easy as `0xdead_beefusize as *const MainloopInner` and doesn't require any unsafe code.

Good point. Not a common thing to do in real code, but I accept that that would indeed work. I stand corrected.

I've addressed the problem in the new version released yesterday. :)

**Comment by Freax13** [comment]
I saw it, thanks for the quick response :)
