### ISSUE TITLE
Documentation typo?

### ISSUE THREAD

**Issue by codecnotsupported** [jnqnfe/pulse-binding-rust#47]
[Doc link](https://docs.rs/libpulse-binding/2.25.0/libpulse_binding/)

In the `Warning` Section:
```
...
it does fit perfectly with the Rust borrow checking mechanism 
and 
thus you cannot rely upon the borrow checker to prevent unsafe use as much as is typical.
```

It fits with the borrow checking mechanism but because of that, you can't rely on the borrow checker?
That seems a bit contradictory.

**Comment by jnqnfe** [comment]
Right, yeah it does seem that I made a typo there. Fixed in new version! Thanks. :)
