### ISSUE TITLE
How to use ListResult?

### ISSUE THREAD

**Issue by kaii-lb** [jnqnfe/pulse-binding-rust#57]
say i have a card, and i need to change the audio profile of that card, so i use `get_card_info_by_name` to get the info of that card to decide what profile to choose. however this returns the info in a `ListResult<&CardInfo>'_>>`, and it doesn't seem i can iterate over it or unwrap it to get the underlying `CardInfo` or anything, how would i get info about a card this way?

**Comment by jnqnfe** [comment]
The concept of `ListResult` _is_ actually documented quite clearly both on the object itself and in the introspection mod docs, though fair enough it is a little unintuitive and I can appreciate some people getting confused.

Any function/method involving `ListResult` must be provided with a callback. Where _n_ is the number of items in the list, your callback will be executed _n + 1_ times. Once for each list item, being passed a `ListItem::Item(T)`, then one final time being passed `ListItem::End` to mark that the end of the list has been reached. (`ListItem::Error` signals that an error occurred whilst iterating over the list).

So the callback you construct must take a `ListItem`, and within the callback you will need a `match` block to cover the different variants. What you do in response to an instance of each variant is up to you, naturally. As a simple example, in response to a `ListItem::Item(T)` you could print the item's details to the screen, in response to `ListItem::Error` you might print an error to the screen, and in response to `ListItem::End` you may not need to bother doing anything.

Note that execution of callbacks is done by the client side mainloop, an instance of which you setup in your code, and which you control through the mainloop lock.

The `Operation` object returned by the likes of `get_card_info_by_name()` allows you some control over the overall list iteration operation, allowing you to check operation status or to cancel.

Essentially you are not simply given a collection of items that you can iterate over yourself directly, you're asking the pulseaudio client to iterate over its items and execute a callback you're providing for each one.

**Comment by kaii-lb** [comment]
ohhhhh thats making sense now, thanks for the explanation <3
