### ISSUE TITLE
How to bind unix signal to mainloop?

### ISSUE THREAD

**Issue by martsa1** [jnqnfe/pulse-binding-rust#59]
I've recently been dabbling with this library to build a small utility for monitoring some pulse audio stuff and have been happy to gradually learn how to get all the bits and pieces I want working. The last part I'd like to integrate is a way to gracefully handle SIGTERM and SIGINT,

Reading through the docs, the [signal](https://docs.rs/libpulse-binding/latest/libpulse_binding/mainloop/signal/index.html) mod appears to offer exactly what I need, but thus far I've been unable to figure out how to actually use it in anger...  Are there any examples to work off of for this?

I got as far as calling the `init_signals` trait method on the threaded mainloop, but I've been unable to figure out how to wire up the mainloop to specific signals.  I was able to create an Event instance, but I've not been able to get it to actually hook into anything yet...

```rust
let mainloop  = pulse::mainloop::threaded::Mainloop::new().unwrap();
mainloop.init_signals().unwrap();
let sigint = pulse::mainloop::signal::Event::new(2, |sig| {trace!("signal handler called")});
```

Thanks in advance,

**Comment by jnqnfe** [comment]
No, no examples, sorry. You might get lucky hunting for examples using the C API and then adapt it to the Rust interface.

It's been a while since I touched the applicable code here, and I had limited understanding of the actual C API when I built it. Taking a quick look, it seems that you'd need to call the `init_signals()` method after creating the mainloop object, letting PA prepare itself for signal handlers to be assigned. Later, prior to destruction of the mainloop object, but presumably after destroying any signal handler objects, you'd want to make sure to call the `signals_done()` method to let PA clean things up and thus avoid any memory leaks or whatever during program termination. For every signal you wish to handle you'd create a `mainloop::signal::Event` object, which I presume you'd want to do outside of and prior to your mainloop so your handlers last across loops. When creating such an `Event` object you specify the number of the signal to handle, and you specify a callback to be executed. Any objects that you want to use within your callback you'd have to share in the same way as with other callbacks, creating extra object references via use of `Rc`/`Arc` that would then be owned by the callback closure. When the signal occurs, PA's own signal handler will catch it and execute the callback you gave.

I don't understand what you mean when you say you can't figure out how to wire up to specific signals; you target specific signals via the UNIX signal ID number when creating the `Event` objects. I also don't follow why you're supposedly unable to 'hook into anything', your code sample looks fine to me at a glance. Perhaps you need to actually create a context, start the mainloop, etc before PA will actually catch the signals and call your callbacks. Perhaps execution of your signal callbacks may even be tied to loop execution like with other callbacks. You're going to have to throw together a full example use of the mainloop as given in the documentation, then add the signal handling. If necessary you might have to build a C example to help figure it out and ask the PA devs if you have any trouble with that.

**Comment by martsa1** [comment]
Thanks for getting back to me so swiftly! Apologies for the poor context, I've chucked together this (very) minimal sample program, the bit I'm struggling with is how the Event callback gets wired into the pulseaudio event loop, and how I can subsequently use that to react to things, here's the code:
```rust
use std::cell::RefCell;
use std::error::Error;
use std::rc::Rc;
use std::sync::mpsc;

use chrono::Local;
use std::io::Write;

use clap::Parser;
use env_logger::Env;
use log::debug;
use log::{info, trace, warn};
use pulse::{
    context::{Context, FlagSet, State},
    mainloop::signal::{Event, MainloopSignals},
    mainloop::threaded::Mainloop,
    proplist::Proplist,
};

#[derive(Parser, Debug)]
#[clap(author = "Sam Martin-Brown", version, about)]
/// Application configuration
struct Args {
    /// whether to be verbose
    #[arg(short = 'v')]
    verbose: bool,

    /// an optional name to greet
    #[arg()]
    name: Option<String>,
}

fn setup_logs() {
    let args = Args::parse();
    let log_env = if args.verbose {
        Env::default().default_filter_or("debug")
    } else {
        Env::default().default_filter_or("info")
    };
    env_logger::Builder::from_env(log_env)
        .format(|buf, record| {
            writeln!(
                buf,
                "{} [{}:{}] ({}): {}",
                Local::now().format("%Y-%m-%dT%H:%M:%S%.6f%z"),
                record.file().unwrap_or("unknown"),
                record.line().unwrap_or(0),
                record.level(),
                record.args(),
            )
        })
        .init();
}

fn setup_unix_signals(
    mainloop: &mut Mainloop,
    sig_data: Rc<RefCell<bool>>,
) -> Result<(), Box<dyn Error>> {
    Event::new(2, move |sig_num| {
        warn!("Received a signal, num {}", sig_num);
        *sig_data.borrow_mut() = true;
    });
    mainloop.init_signals()?;
    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    setup_logs();

    let signal_data = Rc::new(RefCell::new(false));

    let mut mainloop = Mainloop::new().ok_or("mainloop new failed")?;
    let _ = setup_unix_signals(&mut mainloop, Rc::clone(&signal_data));

    let proplist = Proplist::new().ok_or("proplist failed")?;
    let mut context = Context::new_with_proplist(&mainloop, "source-listener", &proplist)
        .ok_or("context::new_with_proplist failed")?;

    info!("Connecting to daemon");
    connect_to_server(&mut context, &mut mainloop)?;


    debug!("waiting for sigint signal");
    mainloop.lock();
    loop {
        mainloop.wait();
        info!("Caught signal from mainloop");
        if *signal_data.borrow() == true {
            info!("Halting");
            return Ok(());
        }
    }
}

fn connect_to_server(context: &mut Context, mainloop: &mut Mainloop) -> Result<(), Box<dyn Error>> {
    trace!("Calling context.connect");
    mainloop.lock();

    let (tx, rx) = mpsc::channel();
    {
        // Context state boxed-callback setup
        trace!("Registering context state callback");
        context.set_state_callback(Some(Box::new(move || {
            tx.send(Some(())).unwrap();
        })));
    }

    context.connect(None, FlagSet::NOAUTOSPAWN, None)?;

    mainloop.unlock();
    mainloop.start()?;

    loop {
        let _ = rx.recv(); // Wait for signal from callback.

        let state = context.get_state();
        match state {
            State::Unconnected | State::Connecting | State::Authorizing | State::SettingName => {
                debug!("Context state: {:?}", state);
                continue; // Use channel for synchronisation
            }
            State::Ready => {
                debug!("Context state: {:?}", state);
                break;
            }
            State::Failed => {
                debug!("Context state: {:?}", state);
                return Err("Context connect failed".into());
            }
            State::Terminated => {
                debug!("Context state: {:?}", state);
                return Err("Context terminated".into());
            }
        }
    }
    // Once connected, we don't care anymore...
    context.set_state_callback(None);

    Ok(())
}

```

Running this, I see logs something like this:
```
PULSE_LOG=4 RUST_LOG=trace target/debug/pulseaudio-sink-listener
Parsing configuration file '/etc/pulse/client.conf'
Failed to open configuration file '/etc/pulse/client.conf.d/01-enable-autospawn.conf': No such file or directory
Using shared memfd memory pool with 1024 slots of size 64.0 KiB each, total size is 64.0 MiB, maximum usable slot size is 65472
2024-06-22T09:01:31.644649+0100 [src/main.rs:81] (INFO): Connecting to daemon
2024-06-22T09:01:31.644727+0100 [src/main.rs:98] (TRACE): Calling context.connect
2024-06-22T09:01:31.644734+0100 [src/main.rs:104] (TRACE): Registering context state callback
Trying to connect to /run/user/1000/pulse/native...
2024-06-22T09:01:31.644854+0100 [src/main.rs:121] (DEBUG): Context state: Connecting
SHM possible: yes
2024-06-22T09:01:31.645172+0100 [src/main.rs:121] (DEBUG): Context state: Authorizing
Protocol version: remote 35, local 35
Negotiated SHM: yes
Memfd possible: yes
Negotiated SHM type: shared memfd
2024-06-22T09:01:31.645467+0100 [src/main.rs:121] (DEBUG): Context state: SettingName
2024-06-22T09:01:31.645574+0100 [src/main.rs:125] (DEBUG): Context state: Ready
2024-06-22T09:01:31.645585+0100 [src/main.rs:85] (DEBUG): waiting for sigint signal
```

However, when I sent a SigInt signal to this process, it terminates abruptly and sets an error return code (same behaviour as with the unix signals part disabled). I'm fairly sure I'm just missing something due to being unfamiliar with the pulseaudio APIs.

(Apologies for the use of MPSC channels, in my little project I found it was trivial enough in scope that that allowed me to coordinate without needing unsafe etc. which felt ergonomic, all the code is really doing is subscribing to sources and reacting when they are muted/unmuted/default source changes - pretty trivial...!)

**Comment by martsa1** [comment]
> I don't understand what you mean when you say you can't figure out how to wire up to specific signals; you target specific signals via the UNIX signal ID number when creating the Event objects. I also don't follow why you're supposedly unable to 'hook into anything', your code sample looks fine to me at a glance.

My initial writing was somewhat vaguely worded, apologies.

In the full sample code above, the part that feels a little confusing to me is that I initialise the signal handling on my mainloop via the trait-function, and I create an Event instance, but there's nothing in the user-facing code that appears to bind that event to my mainloop etc. - naively, I feel like I'd need to do something like `mainloop.register_signal(my_sigint_event)` or something like that, and that would subsequently result in my signal handler callback being triggered?

Studying the implementation of Event though it looks like I need to be careful to retain the Event or it'll clear itself up, perhaps thats what I'm doing incorrectly - it also looks like its able to register a callback for a signal directly, without needing the mainloop.

**Comment by martsa1** [comment]
Indeed, ensuring the Event is not immediately dropped allows the log from the callback to fire..!  Guess I was sleeping when trying this originally.

I think I'd originally been expecting the signal to wind up as some sort of event in pulseaudio that I could subscribe to and thus be able to interrupt a `wait` or `recv` call etc...
