### ISSUE TITLE
Incorrect Null check

### ISSUE THREAD

**Issue by AdriaanPrinsloo** [jnqnfe/pulse-binding-rust#62]
Hi,  I've encountered a situation where an audio device has a null device, but not name.  This causes a panic when I discover the devices on the machine.  The code appears to do a null check for the name, instead of the device.  I've popped a fix into this pull request:  

https://github.com/jnqnfe/pulse-binding-rust/pull/61

Kind Regards,
Adriaan.

**Comment by jnqnfe** [comment]
Oops, yep that's a bug. Merged and published! Thanks!
